// packages/apm-js-angular/src/index.ts
import { ErrorHandler, Injectable } from '@angular/core';
import { Plugin } from '@apm/js';

@Injectable()
export class AngularErrorHandler extends ErrorHandler {
    public client;

    constructor(client?) {
        super();

        this.client = client;
    }

    public handleError(error: any): void {
        const event = {
            errorClass: error.name,
            errorMessage: error.message,
            type: 'unhandledException',
        };

        this.client.dispatcher.dispatch('notify', event);

        ErrorHandler.prototype.handleError.call(this, error);
    }
}

export class AngularPlugin extends Plugin {
    static pluginName: string = 'AngularPlugin';

    constructor(kernel) {
        super(kernel);
    }

    apply() {
        new AngularErrorHandler(this);
    }
}

// packages/apm-js-react/src/index.ts
import { Plugin } from '@apm/js';

export class ReactjsPlugin extends Plugin {
    static pluginName: string = 'ReactjsPlugin';

    constructor(kernel) {
        super(kernel);
    }

    apply() {
        // @ts-ignore
        if (!window.React) {
            throw new Error('Error');
        }

        const dispatcher = this.dispatcher

        // @ts-ignore
        class ErrorBoundary extends window.React.Component {
            constructor(props) {
                super(props);

                this.state = {
                    error: null,
                    info: null,
                };
            }

            componentDidCatch(error, info) {
                const event = {
                    errorClass: error.name,
                    errorMessage: error.message,
                    type: 'unhandledException',
                };

                dispatcher.dispatch('notify', event);
            }

            render() {
                const { error }: any = this.state;
                if (error) {
                    const { FallbackComponent }: any = this.props;
                    if (FallbackComponent) return window.React.createElement(FallbackComponent, this.state);
                    return null;
                }

                return this.props.children;
            }
        }


    }
}
